import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const Navbar = dynamic( () => import("@/components/commons/Navbar"),{ssr:false}) 
import QueryProviders from "@/lib/QueryProviders";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProviders>
          <Navbar />
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
